/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.shipkit.smart.versioning

import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import spock.lang.Specification

/**
 * A simple functional test for the 'org.shipkit.smart.versioning.greeting' plugin.
 */
class SmartVersioningPluginFunctionalTest extends Specification {

    @Rule TemporaryFolder tmp = new TemporaryFolder()

    def "runs task"() {
        // Setup the test build
        new File(rootDir, "settings.gradle") << ""
        new File(rootDir, "build.gradle") << "plugins {  id('org.shipkit.smart.versioning.greeting')}"

        given:
        def result = run("greeting")

        expect:
        result.getOutput().contains("Hello from plugin 'org.shipkit.smart.versioning.greeting'")
    }

    File getRootDir() {
        tmp.root
    }

    def run(String ...args) {
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments(args)
        runner.withProjectDir(rootDir)
        return runner.build()
    }
}
